package engine

import (
	"errors"
	"time"
)

// OpID uniquely identifies an invocation of an engine function.
// Generated by the Engine as a monotonic atomic int64.
type OpID int64

// Event is the sum of everything an engine operation can emit.
// Consumers (CLI drainer, TUI app) type-switch on the concrete type.
type Event interface {
	isEngineEvent()
	GetOpID() OpID
}

// KindOp identifies the operation kind for StartedEvent. Use the typed
// constants below instead of bare strings so the set is discoverable.
type KindOp string

const (
	// KindInstall marks the start of an install op.
	KindInstall KindOp = "install"
	// KindUpdate marks the start of an update op.
	KindUpdate KindOp = "update"
	// KindRemove marks the start of a remove op.
	KindRemove KindOp = "remove"
	// KindImport marks the start of an import op.
	KindImport KindOp = "import"
	// KindFcCache marks the start of the fc-cache refresh sub-phase that
	// follows install/update/remove on Linux.
	KindFcCache KindOp = "fc-cache"
	// KindDoctor marks the start of a doctor op.
	KindDoctor KindOp = "doctor"
	// KindCatalogFetch marks the start of a catalog-refresh op.
	KindCatalogFetch KindOp = "catalog-fetch"
)

// StartedEvent marks the start of a sub-operation. A single op may emit
// multiple StartedEvents to delimit successive sub-phases (e.g. KindInstall
// at op entry, then KindFcCache after extraction completes). For single-
// target ops, OpID and Target coincide with the only element.
type StartedEvent struct {
	OpID   OpID
	Target string // font tag, "" for ops without target (e.g. RunDoctor)
	Kind   KindOp
}

func (e StartedEvent) isEngineEvent() {}
func (e StartedEvent) GetOpID() OpID  { return e.OpID }

// ProgressEvent reports incremental progress of a sub-operation.
// Total = 0 means indeterminate.
type ProgressEvent struct {
	OpID    OpID
	Target  string
	Stage   string // "download", "extract"
	Written int64
	Total   int64
}

func (e ProgressEvent) isEngineEvent() {}
func (e ProgressEvent) GetOpID() OpID  { return e.OpID }

// Level classifies a LogEvent.
type Level int

const (
	LevelInfo Level = iota
	LevelWarn
	LevelError
)

// LogEvent is a human-readable message accompanying the operation.
// The UI may display it in a logpane / stderr based on verbosity.
type LogEvent struct {
	OpID    OpID
	Target  string // "" if op-level
	Level   Level
	Message string
}

func (e LogEvent) isEngineEvent() {}
func (e LogEvent) GetOpID() OpID  { return e.OpID }

// CompletedKind enumerates the outcome of a CompletedEvent.
type CompletedKind int

const (
	CompletedSuccess   CompletedKind = iota
	CompletedSkipped                 // already at the requested state
	CompletedDeadopted               // imported font removed from manifest, files left
)

// CompletedEvent indicates that the sub-op for Target finished successfully.
type CompletedEvent struct {
	OpID     OpID
	Target   string
	Kind     CompletedKind
	Detail   string    // e.g. "installed v3.2.1", "files left on disk"
	NewState *FontInfo // post-op snapshot; nil if not applicable (e.g. remove)
}

func (e CompletedEvent) isEngineEvent() {}
func (e CompletedEvent) GetOpID() OpID  { return e.OpID }

// FailedEvent indicates failure for Target (NOT failure of the whole op —
// the latter is signalled by closing the channel, optionally after a
// FailedEvent with Target="").
type FailedEvent struct {
	OpID      OpID
	Target    string
	Err       error
	Retriable bool   // if true, the caller may retry the same op
	Hint      string // user-facing suggestion
}

func (e FailedEvent) isEngineEvent() {}
func (e FailedEvent) GetOpID() OpID  { return e.OpID }

// CanceledEvent signals cancellation via ctx.Cancel() for Target.
type CanceledEvent struct {
	OpID   OpID
	Target string
}

func (e CanceledEvent) isEngineEvent() {}
func (e CanceledEvent) GetOpID() OpID  { return e.OpID }

// ConflictEvent requests a user decision. The consumer calls
// OpHandle.Resolve(Token, choice) to unblock the operation.
type ConflictEvent struct {
	OpID    OpID
	Target  string
	Kind    ConflictKind
	Choices []ConflictChoice
	Token   int64 // identifies this specific question
	Detail  string
}

func (e ConflictEvent) isEngineEvent() {}
func (e ConflictEvent) GetOpID() OpID  { return e.OpID }

// DoctorSectionEvent is emitted by RunDoctor for each section completed.
//
// One event is emitted per underlying doctor.Check, so a single Section may
// produce multiple events (e.g. "XDG paths" emits one event per probed dir,
// each with a distinct Title).
type DoctorSectionEvent struct {
	OpID    OpID
	Section string // "XDG paths", "fc-cache", "GitHub auth", "Manifest", "Catalog cache", "Orphan directories"
	Title   string // short label within the section, e.g. "font dir", "schema version"
	Status  DoctorStatus
	Detail  string       // human-readable detail; never combined with Hint
	Hint    string       // optional remediation suggestion; empty when Status==DoctorOK
	Action  DoctorAction // None / RefreshCatalog / RefreshFontCache / ...
}

func (e DoctorSectionEvent) isEngineEvent() {}
func (e DoctorSectionEvent) GetOpID() OpID  { return e.OpID }

// DoctorStatus mirrors internal/doctor severity values exposed to engine consumers.
type DoctorStatus int

const (
	DoctorOK DoctorStatus = iota
	DoctorWarn
	DoctorFail
	DoctorSkip // section not applicable (e.g. fc-cache on macOS)
)

// DoctorAction enumerates actions the TUI may propose for a FAIL/WARN section.
type DoctorAction int

const (
	ActionNone DoctorAction = iota
	ActionRefreshCatalog
	ActionRefreshFontCache
)

// FontInfo is the user-facing representation of a font, derived from
// catalog + manifest.
type FontInfo struct {
	Name          string
	Status        FontStatus
	Version       string    // installed version; "" if NotInstalled or Imported
	LatestVersion string    // from catalog; "" if catalog missing
	Files         []string  // installed file paths (absolute); nil if not installed
	Size          int64     // total bytes on disk; 0 if not installed
	InstalledAt   time.Time // zero if not installed
	Dir           string    // install dir; "" if not installed
}

// FontStatus discriminates the state of a font for rendering purposes.
type FontStatus int

const (
	StatusAvailable FontStatus = iota // in catalog, not installed
	StatusInstalled                   // managed by lazynf, valid release tag
	StatusImported                    // adopted from disk, "imported" sentinel
	StatusStale                       // installed at a tag != latest
	StatusUnknown                     // not in catalog (exists in manifest but vanished upstream)
)

// ErrNotInCatalog is returned synchronously by Install/Update if the tag is
// not in the catalog.
var ErrNotInCatalog = errors.New("font not in catalog")
